apiVersion: apps/v1
kind:  Deployment
metadata:
  name: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: node-app
        image: docker.io/devworksit/app:v2
        ports:
        - containerPort: 3333
