FROM node:lts-alpine
WORKDIR /usr/src/app
RUN npm install -g yarn --force
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
EXPOSE 3333
ENV NODE_ENV development
ENV PORT 3333
CMD ["yarn", "dev"]
